[package]
name = "lemmy_db_views"
version = "0.13.5-rc.7"
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"

[lib]
doctest = false

[dependencies]
lemmy_db_schema = { version = "=0.13.5-rc.7", path = "../db_schema" }
diesel = { version = "1.4.8", features = ["postgres","chrono","serde_json"] }
serde = { version = "1.0.130", features = ["derive"] }
log = "0.4.14"
url = "2.2.2"

[dev-dependencies]
serial_test = "0.5.1"
