[package]
name = "lemmy_db_views"
version = "0.16.5"
edition = "2021"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"
rust-version = "1.57"

[lib]
doctest = false

[features]
full = ["lemmy_db_schema/full", "diesel", "diesel-async", "diesel_ltree", "tracing"]

[dependencies]
lemmy_db_schema = { version = "=0.16.5", path = "../db_schema" }
diesel = { version = "2.0.2", features = ["postgres","chrono","serde_json"], optional = true }
diesel-async = { version = "0.1.1", features = ["postgres", "bb8"], optional = true}
diesel_ltree = { version = "0.3.0", optional = true}
serde = { version = "1.0.147", features = ["derive"] }
tracing = { version = "0.1.36", optional = true }
typed-builder = "0.10.0"
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
serial_test = "0.9.0"
tokio = "1.21.2"
