[package]
name = "lemmy_routes"
version = "0.14.4-rc.4"
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"

[lib]
doctest = false

[dependencies]
lemmy_utils = { version = "=0.14.4-rc.4", path = "../utils" }
lemmy_websocket = { version = "=0.14.4-rc.4", path = "../websocket" }
lemmy_db_views = { version = "=0.14.4-rc.4", path = "../db_views" }
lemmy_db_views_actor = { version = "=0.14.4-rc.4", path = "../db_views_actor" }
lemmy_db_schema = { version = "=0.14.4-rc.4", path = "../db_schema" }
lemmy_api_common = { version = "=0.14.4-rc.4", path = "../api_common" }
lemmy_apub = { version = "=0.14.4-rc.4", path = "../apub" }
diesel = "1.4.8"
actix = "0.12.0"
actix-web = { version = "4.0.0-beta.9", default-features = false, features = ["rustls"] }
actix-web-actors = { version = "4.0.0-beta.7", default-features = false }
actix-http = "3.0.0-beta.10"
sha2 = "0.9.8"
anyhow = "1.0.44"
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.18"
reqwest = { version = "0.11.7", features = ["stream"] }
reqwest-middleware = "0.1.2"
rss = "1.10.0"
serde = { version = "1.0.130", features = ["derive"] }
url = { version = "2.2.2", features = ["serde"] }
strum = "0.21.0"
once_cell = "1.8.0"
tracing = "0.1.29"
tokio = { version = "1", features = ["sync"] }
