[package]
name = "lemmy_utils"
version = "0.16.4-rc.11"
edition = "2021"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"
homepage = "https://join-lemmy.org/"
documentation = "https://join-lemmy.org/docs/en/index.html"

[lib]
name = "lemmy_utils"
path = "src/lib.rs"
doctest = false

[features]
full = ["http", "regex", "chrono", "lettre", "tracing", "itertools", "serde_json", "rand", "comrak", "once_cell",
    "reqwest-middleware", "strum", "strum_macros", "futures", "diesel", "deser-hjson", "smart-default",
    "jsonwebtoken", "doku", "uuid", "html2text", "rosetta-i18n", "parking_lot"]

[dependencies]
url = { version = "2.2.2", features = ["serde"] }
anyhow = "1.0.56"
tracing-error = "0.2.0"
serde = { version = "1.0.136", features = ["derive"] }
actix-web = { version = "4.0.1", default-features = false, features = ["rustls"] }
http = {version = "0.2.6", optional = true }
regex = { version = "1.5.5", optional = true }
chrono = { version = "0.4.19", features = ["serde", "clock"], default-features = false, optional = true }
lettre = { version = "0.10.0-rc.6", optional = true }
tracing = { version = "0.1.32", optional = true }
itertools = { version = "0.10.3", optional = true }
serde_json = { version = "1.0.79", features = ["preserve_order"], optional = true }
rand = { version = "0.8.5", optional = true }
comrak = { version = "0.12.1", default-features = false, optional = true }
once_cell = { version = "1.10.0", optional = true }
reqwest-middleware = { version = "0.1.5", optional = true }
strum = { version = "0.24.0", optional = true }
strum_macros = { version = "0.24.0", optional = true }
futures = { version = "0.3.21", optional = true }
diesel = { version = "1.4.8", optional = true }
deser-hjson = { version = "1.0.2", optional = true }
smart-default = { version = "0.6.0", optional = true }
jsonwebtoken = { version = "8.0.1", optional = true }
doku = { version = "0.11.0", optional = true }
uuid = { version = "0.8.2", features = ["serde", "v4"], optional = true }
html2text = { version = "0.3.1", optional = true }
rosetta-i18n = { version = "0.1.2", optional = true }
parking_lot = { version = "0.12.0", optional = true }

[build-dependencies]
rosetta-build = "0.1.2"
