[package]
name = "lemmy_db_views_actor"
version = "0.13.1"
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"

[lib]
doctest = false

[dependencies]
lemmy_db_queries = { version = "=0.13.1", path = "../db_queries" }
lemmy_db_schema = { version = "=0.13.1", path = "../db_schema" }
diesel = { version = "1.4.8", features = ["postgres","chrono","r2d2","serde_json"] }
serde = { version = "1.0.130", features = ["derive"] }
